
include( "properties/bone_manipulate.lua" )
include( "properties/remove.lua" )
include( "properties/statue.lua" )
include( "properties/keep_upright.lua" )
include( "properties/persist.lua" )
include( "properties/drive.lua" )
include( "properties/ignite.lua" )
include( "properties/collisions.lua" )
include( "properties/gravity.lua" )
include( "properties/npc_scale.lua" )
include( "properties/editentity.lua" )
include( "properties/kinect_controller.lua" )
include( "properties/bodygroups.lua" )
include( "properties/skin.lua" )

