---- Autodownload resources

resource.AddFile("materials/vgui/ttt/custom_marker.vmt")
resource.AddFile("materials/vgui/ttt/det_beacon.vmt")
resource.AddFile("materials/vgui/ttt/icon_armor.vmt")
resource.AddFile("materials/vgui/ttt/icon_beacon.vmt")
resource.AddFile("materials/vgui/ttt/icon_binoc.vmt")
resource.AddFile("materials/vgui/ttt/icon_bullet.vmt")
resource.AddFile("materials/vgui/ttt/icon_c4.vmt")
resource.AddFile("materials/vgui/ttt/icon_c4warn.vmt")
resource.AddFile("materials/vgui/ttt/icon_cbar.vmt")
resource.AddFile("materials/vgui/ttt/icon_code.vmt")
resource.AddFile("materials/vgui/ttt/icon_corpse.vmt")
resource.AddFile("materials/vgui/ttt/icon_cse.vmt")
resource.AddFile("materials/vgui/ttt/icon_deagle.vmt")
resource.AddFile("materials/vgui/ttt/icon_defuser.vmt")
resource.AddFile("materials/vgui/ttt/icon_det.vmt")
resource.AddFile("materials/vgui/ttt/icon_disguise.vmt")
resource.AddFile("materials/vgui/ttt/icon_fall.vmt")
resource.AddFile("materials/vgui/ttt/icon_fire.vmt")
resource.AddFile("materials/vgui/ttt/icon_flare.vmt")
resource.AddFile("materials/vgui/ttt/icon_foot.vmt")
resource.AddFile("materials/vgui/ttt/icon_glock.vmt")
resource.AddFile("materials/vgui/ttt/icon_halp.vmt")
resource.AddFile("materials/vgui/ttt/icon_head.vmt")
resource.AddFile("materials/vgui/ttt/icon_health.vmt")
resource.AddFile("materials/vgui/ttt/icon_id.vmt")
resource.AddFile("materials/vgui/ttt/icon_inno.vmt")
resource.AddFile("materials/vgui/ttt/icon_knife.vmt")
resource.AddFile("materials/vgui/ttt/icon_lastid.vmt")
resource.AddFile("materials/vgui/ttt/icon_launch.vmt")
resource.AddFile("materials/vgui/ttt/icon_list.vmt")
resource.AddFile("materials/vgui/ttt/icon_m16.vmt")
resource.AddFile("materials/vgui/ttt/icon_m249.vmt")
resource.AddFile("materials/vgui/ttt/icon_mac.vmt")
resource.AddFile("materials/vgui/ttt/icon_nades.vmt")
resource.AddFile("materials/vgui/ttt/icon_pistol.vmt")
resource.AddFile("materials/vgui/ttt/icon_polter.vmt")
resource.AddFile("materials/vgui/ttt/icon_radar.vmt")
resource.AddFile("materials/vgui/ttt/icon_radio.vmt")
resource.AddFile("materials/vgui/ttt/icon_rock.vmt")
resource.AddFile("materials/vgui/ttt/icon_rpg.vmt")
resource.AddFile("materials/vgui/ttt/icon_scout.vmt")
resource.AddFile("materials/vgui/ttt/icon_shotgun.vmt")
resource.AddFile("materials/vgui/ttt/icon_silenced.vmt")
resource.AddFile("materials/vgui/ttt/icon_skull.vmt")
resource.AddFile("materials/vgui/ttt/icon_splode.vmt")
resource.AddFile("materials/vgui/ttt/icon_time.vmt")
resource.AddFile("materials/vgui/ttt/icon_tport.vmt")
resource.AddFile("materials/vgui/ttt/icon_traitor.vmt")
resource.AddFile("materials/vgui/ttt/icon_ump.vmt")
resource.AddFile("materials/vgui/ttt/icon_wtester.vmt")
resource.AddFile("materials/vgui/ttt/sample_scan.vmt")
resource.AddFile("materials/vgui/ttt/score_logo.vmt")
resource.AddFile("materials/vgui/ttt/slotcap.vmt")
resource.AddFile("materials/vgui/ttt/sprite_traitor.vmt")
resource.AddFile("materials/vgui/ttt/tbut_hand_line.vmt")
resource.AddFile("materials/vgui/ttt/tbut_hand_filled.vmt")

resource.AddFile("materials/vgui/ttt/c4_bomb.vmt")
resource.AddFile("materials/vgui/ttt/c4_cut.vmt")
resource.AddFile("materials/vgui/ttt/c4_wire.vmt")
resource.AddFile("materials/vgui/ttt/c4_wire_cut.vmt")

resource.AddFile("materials/vgui/ttt/help/tut01.vmt")
resource.AddFile("materials/vgui/ttt/help/tut02.vmt")
resource.AddFile("materials/vgui/ttt/help/tut03.vmt")
resource.AddFile("materials/vgui/ttt/help/tut04.vmt")
resource.AddFile("materials/vgui/ttt/help/tut05.vmt")
resource.AddFile("materials/vgui/ttt/help/tut06.vmt")

resource.AddFile("materials/models/ttt/deerstalker/deerstalker.vmt")
resource.AddFile("models/ttt/deerstalker.mdl")

resource.AddFile("materials/sprites/scope.vmt")

resource.AddFile("sound/ttt/thump01e.mp3")
resource.AddFile("sound/ttt/thump02e.mp3")
resource.AddFile("sound/ttt/wirecut.mp3")

